### ISSUE TITLE
[222+] Migration Aura Flow wrapper to LWC

### ISSUE THREAD

**Issue by muenzpraeger** [trailheadapps/purealoe-lwc#29]
**What is missing from the application? Please describe.**
Currently the application uses an Aura component for wrapping LWCs that are used in Flow (see [here](https://github.com/trailheadapps/purealoe-lwc/tree/master/force-app/main/default/aura/irrigationManagerWrapper)).

**Describe the solution you'd like**
Once the new metadata target is available for flow screens the wrapper should be removed.

**Comment by satyasekharcvb** [comment]
Implemented with Winter'20 release.
